import "./globals.css";
import NavBar from "./components/NavBar"
import Header from "./components/Header";
import ModalReturn from "./components/modals/ModalReturn";
import ModalSuccess from "./components/modals/ModalSuccess";
import ModalNotAvailable from "./components/modals/ModalNotAvailable";
import ModalBorrow from "./components/modals/ModalBorrow"
import { ReactQueryProvider } from "./components/ReactQueryProvider";

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout(
  props: {
  children: React.ReactNode,
  transact: React.ReactNode;
}) {
  <link rel="icon" href="/favicon.ico" sizes="any" />
  const isDark = false
  const bgColor = isDark? 'bg-slate-900' : 'bg-gradient-to-r from-neutral-50 to-neutral-200'
  return (
    <html lang="en">
      <body className={`font-sans${bgColor}`}>
        <header className="w-full min-w-screen"><Header/></header>
        <ReactQueryProvider>
          <main>
            {props.children}
          </main>
        {/*  {props.transact} */}
          <ModalBorrow />
          <ModalNotAvailable/>
        </ReactQueryProvider>
{/*         <ModalReturn />
        <ModalSuccess />
          */}
      </body>
    </html>
  )
}
