import "./globals.css";
import NavBar from "./components/NavBar"
import Header from "./components/Header";
import ModalReturn from "./components/modals/ModalReturn";
import ModalSuccess from "./components/modals/ModalSuccess";
import ModalNotAvailable from "./components/modals/ModalNotAvailable";
import ModalBorrow from "./components/modals/ModalBorrow"
import { ReactQueryProvider } from "./components/ReactQueryProvider";
import ModalChangeOwner from "./components/modals/ModalChangeOwner";

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout(
  props: {
  children: React.ReactNode,
  transact: React.ReactNode;
}) {
  <link rel="icon" href="/favicon.ico" sizes="any" />
  const isDark = false
  const bgColor = isDark? 'bg-slate-900' : 'bg-gradient-to-r from-neutral-50 to-neutral-200'

  return (
    <html lang="en">
      <body className={`font-sans${bgColor}`}>
      <ReactQueryProvider>
        <header className="fixed w-full min-w-screen z-[10] bg-white"><Header/></header>
        
          <main className="pt-[65px]">
            {props.children}
          </main>
          <ModalBorrow />
          <ModalNotAvailable/>
          <ModalReturn />
          <ModalSuccess />
          <ModalChangeOwner />
      </ReactQueryProvider>
      </body>
    </html>
  )
}
