import "./globals.css";
import NavBar from "./components/NavBar"
import Header from "./components/Header";
import ModalReturn from "./components/ModalReturn";
import ModalSuccess from "./components/ModalSuccess";
import ModalBorrow from "./components/ModalBorrow";
import ModalNotAvailable from "./components/ModalNotAvailable";

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  <link rel="icon" href="/favicon.ico" sizes="any" />
  const isDark = false
  const bgColor = isDark? 'bg-slate-900' : 'bg-gradient-to-r from-neutral-50 to-neutral-200'
  return (
    <html lang="en">
      <body className={`font-sans${bgColor}`}>
        <header className="w-full min-w-screen"><Header/></header>
        <main>{children}</main>
        <ModalBorrow/>
        <ModalReturn />
        <ModalSuccess />
        <ModalNotAvailable/>
      </body>
    </html>
  )
}
